export interface Post {
  sNo: number
  postCode: string
  postName: string
  ministry: string
}

export const posts: Post[] = [
  { sNo: 1, postCode: "B01", postName: "Inspector (Examiner)", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 2, postCode: "B02", postName: "Inspector (Preventive Officer)", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 3, postCode: "B03", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Employees Provident Fund Organisation (EPFO), Ministry of Labour & Employment" },
  { sNo: 4, postCode: "B04", postName: "Inspector (Central Excise)", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 5, postCode: "B05", postName: "Assistant Enforcement Officer", ministry: "Enforcement Directorate, Ministry of Finance" },
  { sNo: 6, postCode: "B06", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "National Informatics Centre, Ministry of Electronics and Information Technology" },
  { sNo: 7, postCode: "B07", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Central Administrative Tribunal (CAT)" },
  { sNo: 8, postCode: "B08", postName: "Inspector", ministry: "Central Bureau of Narcotics, Ministry of Finance" },
  { sNo: 9, postCode: "B09", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Ministry of External Affairs (MEA)" },
  { sNo: 10, postCode: "B10", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Election Commission of India" },
  { sNo: 11, postCode: "B11", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Ministry of Electronics and Information Technology" },
  { sNo: 12, postCode: "B12", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Intelligence Bureau (IB), Ministry of Home Affairs" },
  { sNo: 13, postCode: "B13", postName: "Sub Inspector (CBI)", ministry: "Central Bureau of Investigation (CBI), Ministry of Personnel, Public Grievances & Pensions" },
  { sNo: 14, postCode: "B14", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Ministry of Railways" },
  { sNo: 15, postCode: "B15", postName: "Inspector Of Income Tax", ministry: "Central Board of Direct Taxes, Ministry of Finance" },
  { sNo: 16, postCode: "B16", postName: "Assistant Section Officer (ASO)", ministry: "Department of Personnel and Training (ASO in CSS), Ministry of Personnel, Public Grievances & Pensions" },
  { sNo: 17, postCode: "B17", postName: "Assistant Section Officer", ministry: "O/o JS & CAO, Armed Forces Headquarters (AFHQ), Ministry of Defence" },
  { sNo: 18, postCode: "B18", postName: "Assistant", ministry: "Ministry of Tourism" },
  { sNo: 19, postCode: "B19", postName: "Inspector of Posts", ministry: "Department of Posts, Ministry of Communication" },
  { sNo: 20, postCode: "B20", postName: "Executive Assistant", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 21, postCode: "B21", postName: "Assistant with grade pay (4200)", ministry: "Enforcement Directorate, Ministry of Finance" },
  { sNo: 22, postCode: "B22", postName: "Assistant with grade pay (4200)", ministry: "Telecom Regulatory Authority of India (TRAI), Ministry of Communications" },
  { sNo: 23, postCode: "B23", postName: "Assistant with grade pay (4200)", ministry: "Department of Official Language, Ministry of Home Affairs" },
  { sNo: 24, postCode: "B24", postName: "Assistant with grade pay (4200)", ministry: "Ministry of Corporate Affairs" },
  { sNo: 25, postCode: "B25", postName: "Assistant with grade pay (4200)", ministry: "Ministry of Mines" },
  { sNo: 26, postCode: "B26", postName: "Assistant with grade pay (4200)", ministry: "Ministry of Textiles" },
  { sNo: 27, postCode: "B27", postName: "Assistant with grade pay (4200)", ministry: "Department of Indian Coast Guard, Ministry of Defence" },
  { sNo: 28, postCode: "B28", postName: "Assistant with grade pay (4200)", ministry: "Directorate of Forensic Science Services (DFSS), Ministry of Home Affairs" },
  { sNo: 29, postCode: "B29", postName: "Assistant/Assistant Section Officer(ASO) with grade pay (4600)", ministry: "Narcotics Control Bureau, Ministry of Home Affairs" },
  { sNo: 30, postCode: "B30", postName: "Sub-Inspector /JIO (NCB)", ministry: "Narcotics Control Bureau, Ministry of Home Affairs" },
  { sNo: 31, postCode: "B31", postName: "Sub Inspector (NIA)", ministry: "National Investigation Agency (NIA), Department of Internal Security, Ministry of Home Affairs" },
  { sNo: 32, postCode: "B32", postName: "Assistant with grade pay (4200)", ministry: "Ministry of Statistics & Programme Implementation" },
  { sNo: 33, postCode: "B33", postName: "Office Superintendent", ministry: "Central Board of Direct Taxes (CBDT), Ministry of Finance" },
  { sNo: 34, postCode: "B34", postName: "Section Head", ministry: "Directorate General of Foreign Trade, Ministry of Commerce & Industry" },
  { sNo: 35, postCode: "B35", postName: "Assistant", ministry: "Department of Commerce, Ministry of Commerce & Industry" },
  { sNo: 36, postCode: "D38", postName: "Accountant/Junior Accountant", ministry: "Comptroller & Auditor General of India (C&AG)" },
  { sNo: 37, postCode: "D39", postName: "Auditor", ministry: "Controller General of Defence Accounts (CGDA), Ministry of Defence" },
  { sNo: 38, postCode: "D40", postName: "Accountant/Junior Accountant", ministry: "Department of Posts, Ministry of Communications" },
  { sNo: 39, postCode: "D41", postName: "Accountant/Junior Accountant", ministry: "CGCA (Controller General of Communication Accounts), Ministry of Communications" },
  { sNo: 40, postCode: "D42", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Office of Development Commissioner, Ministry of Micro, Small and Medium Enterprises" },
  { sNo: 41, postCode: "D43", postName: "Tax Assistant", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 42, postCode: "D44", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Science and Technology, Ministry of Science & Technology" },
  { sNo: 43, postCode: "D45", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Central Bureau of Narcotics, Ministry of Finance" },
  { sNo: 44, postCode: "D46", postName: "Sub-Inspector(Narcotics) - 2400", ministry: "Central Bureau of Narcotics, Ministry of Finance" },
  { sNo: 45, postCode: "D47", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Ministry of Mines" },
  { sNo: 46, postCode: "D48", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Director General Defence Estates(DGDE), Ministry of Defence" },
  { sNo: 47, postCode: "D49", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Ministry of Electronics and Information Technology" },
  { sNo: 48, postCode: "D50", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Ministry of Textiles" },
  { sNo: 49, postCode: "D51", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Water Resources, River Development and Ganga Rejuvenation" },
  { sNo: 50, postCode: "D52", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA) *(Only for Male Candidates)", ministry: "Border Roads Organization (BRO), Ministry of Defence" },
  { sNo: 51, postCode: "D53", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Agriculture Cooperation and Farmers Welfare, Ministry of Agriculture & Farmers Welfare" },
  { sNo: 52, postCode: "D54", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Directorate General of Health Services, Ministry of Health & Family Welfare" },
  { sNo: 53, postCode: "D55", postName: "Tax Assistant", ministry: "Central Board of Direct Taxes (CBDT), Ministry of Finance" },
  { sNo: 54, postCode: "D56", postName: "Upper Division Clerk(UDC)", ministry: "Department of Consumer Affairs, Ministry of Consumer Affairs, Food and Public Distribution" },
  { sNo: 55, postCode: "D57", postName: "Upper Division Clerk(UDC)", ministry: "Narcotics Control Bureau, Ministry of Home Affairs" },
]
