export interface Post {
  sNo: number
  postCode: string
  ministry: string
}

export const posts: Post[] = [
  { sNo: 1, postCode: "L01", ministry: "Central Administrative Tribunal" },
  { sNo: 2, postCode: "L02", ministry: "Department of Internal Security, Intelligence Bureau, Ministry of Home Affairs" },
  { sNo: 3, postCode: "L03", ministry: "Department of Science and Technology, Ministry of Science and Technology" },
  { sNo: 4, postCode: "L04", ministry: "Department of Defence, Canteen Stores Department (CSD), Ministry of Defence" },
  { sNo: 5, postCode: "L05", ministry: "Department of Telecommunications, Ministry of Communications" },
  { sNo: 6, postCode: "L06", ministry: "Ministry of Mines" },
  { sNo: 7, postCode: "L07", ministry: "Department of Food and Public Distribution, Ministry of Consumer Affairs, Food, & Public Distribution" },
  { sNo: 8, postCode: "L08", ministry: "National Commission for Scheduled Tribes" },
  { sNo: 9, postCode: "L09", ministry: "Directorate of Forensic Science Services, Central Forensic Science Laboratory, Ministry of Home Affairs" },
  { sNo: 10, postCode: "L10", ministry: "Department of Posts, Ministry of Communications" },
  { sNo: 11, postCode: "L11", ministry: "Department of Consumer Affairs, Ministry of Consumer Affairs, Food, & Public Distribution" },
  { sNo: 12, postCode: "L12", ministry: "Department of Personnel and Training, Central Bureau of Investigation (CBI), Ministry of Personnel, Public Grievances & Pensions" },
  { sNo: 13, postCode: "L13", ministry: "Niti Aayog" },
  { sNo: 14, postCode: "L14", ministry: "Department of Internal Security, National Investigation Agency, Ministry of Home Affairs" },
  { sNo: 15, postCode: "L15", ministry: "Department of Commerce, Ministry of Commerce & Industry" },
  { sNo: 16, postCode: "L16", ministry: "Department of Defence, Border Roads Organization (BRO), Ministry of Defence (* Only for Male candidates)" },
  { sNo: 17, postCode: "L17", ministry: "Ministry of Electronics and Information Technology" },
  { sNo: 18, postCode: "L18", ministry: "Election Commission of India" },
  { sNo: 19, postCode: "L19", ministry: "Ministry of Statistics & Programme Implementation (Admin-III)" },
  { sNo: 20, postCode: "L20", ministry: "Department of Expenditure, Controller General of Accounts, Ministry of Finance" },
  { sNo: 21, postCode: "L21", ministry: "Department of Defence Production, Directorate General of Aeronautical Quality Assurance (DGAQA), Ministry of Defence" },
  { sNo: 22, postCode: "L22", ministry: "Ministry of Tourism" },
  { sNo: 23, postCode: "L23", ministry: "Department for Promotion of Industry and Internal Trade, Ministry of Commerce & Industry" },
  { sNo: 24, postCode: "L24", ministry: "Department of Defence, Directorate of Public Relations, Ministry of Defence" },
  { sNo: 25, postCode: "L25", ministry: "Department of Agriculture Cooperation and Farmers Welfare, Ministry of Agriculture & Farmers Welfare" },
  { sNo: 26, postCode: "L26", ministry: "Ministry of Civil Aviation" },
  { sNo: 27, postCode: "L27", ministry: "Ministry of Information & Broadcasting" },
  { sNo: 28, postCode: "L28", ministry: "Central Vigilance Commission" },
  { sNo: 29, postCode: "L29", ministry: "Department of Telecommunications, CGCA (Controller General of Communication Accounts), Ministry of Communications" },
  { sNo: 30, postCode: "L30", ministry: "Department of Financial Services, Ministry of Finance" },
  { sNo: 31, postCode: "L31", ministry: "Ministry of Housing & Urban Affairs" },
  { sNo: 32, postCode: "L32", ministry: "Directorate General of Health Services, Ministry of Health and Family Welfare" },
  { sNo: 33, postCode: "L33", ministry: "Ministry of Labour & Employment" },
  { sNo: 34, postCode: "L34", ministry: "Department of Water Resources, River Development and Ganga Rejuvenation, Ministry of Jal Shakti" },
  { sNo: 35, postCode: "L35", ministry: "Department of Defence, Controller General Of Defence Accounts (CGDA), Ministry of Defence" },
  { sNo: 36, postCode: "L36", ministry: "Department of Defence, Indian Coast Guard, Ministry of Defence" },
  { sNo: 37, postCode: "L37", ministry: "National Informatics Centre, Ministry of Electronics and Information Technology" },
  { sNo: 38, postCode: "L38", ministry: "Department of Animal Husbandry and Dairying, Ministry of Fisheries, Animal Husbandry and Dairying" },
  { sNo: 39, postCode: "L39", ministry: "Ministry of Culture" },
  { sNo: 40, postCode: "L40", ministry: "Ministry of Environment, Forest and Climate Change" },
  { sNo: 41, postCode: "L41", ministry: "Central Translation Bureau, Department of Official Language, Ministry of Home Affairs" },
  { sNo: 42, postCode: "L42", ministry: "Armed Forces Headquarters, O/o JS & CAO, Ministry of Defence" },
  { sNo: 43, postCode: "L43", ministry: "Central Electricity Authority, Ministry of Power" },
  { sNo: 44, postCode: "L44", ministry: "Lal Bahadur Shastri National Academy of Administration, Ministry of Personnel, Public Grievances & Pensions" },
  { sNo: 45, postCode: "L45", ministry: "O/o Registrar General of India, Ministry of Home Affairs" },
  { sNo: 46, postCode: "L46", ministry: "National Disaster Response Force Academy, Ministry of Home Affairs" },
  { sNo: 47, postCode: "L47", ministry: "Directorate of Enforcement, Department of Revenue, Ministry of Finance" },
  { sNo: 48, postCode: "L48", ministry: "Ministry of Textiles" },
  { sNo: 49, postCode: "L49", ministry: "Department of Official Language, Central Hindi Training Institute, Ministry of Home Affairs" },
  { sNo: 50, postCode: "L50", ministry: "Ministry of Ports, Shipping and Waterways" },
  { sNo: 51, postCode: "L51", ministry: "Department of Fisheries, Ministry of Fisheries, Animal Husbandry and Dairying" },
  { sNo: 52, postCode: "L52", ministry: "Archeological Survey of India, Ministry of Culture" },
  { sNo: 53, postCode: "L53", ministry: "Central Government Health Scheme (HQs), Ministry of Health and Family Welfare" },
  { sNo: 54, postCode: "D54", ministry: "Staff Selection Commission, Ministry of Personnel, Public Grievances & Pensions" },
  { sNo: 55, postCode: "D55", ministry: "Department of Expenditure, Controller General of Accounts, Ministry of Finance" },
  { sNo: 56, postCode: "D56", ministry: "Ministry of Culture" },
]
