export interface Post {
  sNo: number
  postCode: string
  postName: string
  ministry: string
}

export const posts: Post[] = [
  { sNo: 1, postCode: "B03", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Department of Personnel and Training (ASO in CSS), Ministry of Personnel, Public Grievances & Pensions" },
  { sNo: 2, postCode: "B04", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Intelligence Bureau (IB), Ministry of Home Affairs" },
  { sNo: 3, postCode: "B05", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Ministry of Railways" },
  { sNo: 4, postCode: "B06", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Ministry of External Affairs" },
  { sNo: 5, postCode: "B07", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Armed Force Head Quarter (AFHQ), Ministry of Defence" },
  { sNo: 6, postCode: "B08", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Election Commission of India" },
  { sNo: 7, postCode: "B09", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "National Informatics Centre, Ministry of Electronics and Information Technology" },
  { sNo: 8, postCode: "B10", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Ministry of Electronics and Information Technology" },
  { sNo: 9, postCode: "B11", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Central Administrative Tribunal (CAT)" },
  { sNo: 10, postCode: "B12", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Ministry of Parliamentary Affairs" },
  { sNo: 11, postCode: "B14", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Central Information Commission (CIC)" },
  { sNo: 12, postCode: "B16", postName: "Inspector (Central Excise)", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 13, postCode: "B17", postName: "Inspector (Preventive Officer)", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 14, postCode: "B18", postName: "Inspector (Examiner)", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 15, postCode: "B19", postName: "Assistant Enforcement Officer", ministry: "Enforcement Directorate, Ministry of Finance" },
  { sNo: 16, postCode: "B20", postName: "Inspector Of Posts", ministry: "Department of Posts, Ministry of Communications" },
  { sNo: 17, postCode: "B21", postName: "Inspector Of Income Tax", ministry: "Central Board of Direct Taxes (CBDT), Ministry of Finance" },
  { sNo: 18, postCode: "B22", postName: "Sub Inspector (CBI)", ministry: "Central Bureau of Investigation (CBI), Ministry of Personnel, Public Grievances & Pensions" },
  { sNo: 19, postCode: "B23", postName: "Assistant", ministry: "Ministry of Textiles" },
  { sNo: 20, postCode: "B24", postName: "Assistant", ministry: "Ministry of Mines" },
  { sNo: 21, postCode: "B25", postName: "Assistant", ministry: "Indian Meteorological Department, Ministry of Earth Sciences" },
  { sNo: 22, postCode: "B26", postName: "Assistant", ministry: "Central Passport Office, Ministry of External Affairs" },
  { sNo: 23, postCode: "B27", postName: "Assistant", ministry: "Indian Coast Guard, Ministry of Defence" },
  { sNo: 24, postCode: "B28", postName: "Assistant", ministry: "Enforcement Directorate, Ministry of Finance" },
  { sNo: 25, postCode: "B30", postName: "Assistant", ministry: "Telecom Regulatory Authority of India, Ministry of Communications" },
  { sNo: 26, postCode: "B31", postName: "Sub Inspector (NIA)", ministry: "National Investigation Agency (NIA), Ministry of Home Affairs" },
  { sNo: 27, postCode: "B32", postName: "Executive Assistant", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 28, postCode: "B33", postName: "Research Assistant", ministry: "National Human Rights Commission (NHRC)" },
  { sNo: 29, postCode: "B34", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Central Vigilance Commission (CVC)" },
  { sNo: 30, postCode: "B34", postName: "Inspector", ministry: "Central Bureau of Narcotics, Ministry of Finance" },
  { sNo: 31, postCode: "B35", postName: "Assistant", ministry: "Armed Forces Tribunal" },
  { sNo: 32, postCode: "B36", postName: "Assistant", ministry: "Directorate of Forensic Science Services(DFSS), Ministry of Home Affairs" },
  { sNo: 33, postCode: "B37", postName: "Assistant", ministry: "National Company Law Appelate Tribunal (NCLAT), Ministry of Corporate Affairs" },
  { sNo: 34, postCode: "B38", postName: "Assistant", ministry: "National Company Law Tribunal (NCLT), Ministry of Corporate Affairs" },
  { sNo: 35, postCode: "B39", postName: "Assistant", ministry: "Ministry of Statistics & Programme Implementation (Admin-III)" },
  { sNo: 36, postCode: "B40", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Ministry of Corporate Affairs" },
  { sNo: 37, postCode: "B41", postName: "Assistant/Assistant Section Officer(ASO)", ministry: "Narcotics Control Bureau, Ministry of Home Affairs" },
  { sNo: 38, postCode: "B42", postName: "Divisional Accountant", ministry: "Comptroller & Auditor General of India (C&AG)" },
  { sNo: 39, postCode: "B43", postName: "Section Head", ministry: "Directorate General of Foreign Trade (Ministry of Commerce & Industry)" },
  { sNo: 40, postCode: "B44", postName: "Sub-Inspector/JIO (NCB)", ministry: "Narcotics Control Bureau, Ministry of Home Affairs" },
  { sNo: 41, postCode: "C01", postName: "Junior Statistical Officer", ministry: "Subordinate Statistical Services Division, Ministry of Statistics & Programme Implementation" },
  { sNo: 42, postCode: "C02", postName: "Statistical Investigator Grade-II", ministry: "Registrar General of India and Census Commissioner of India, Department of States, Ministry of Home Affairs" },
  { sNo: 43, postCode: "D01", postName: "Auditor", ministry: "Comptroller & Auditor General of India (C&AG)" },
  { sNo: 44, postCode: "D02", postName: "Accountant/Junior Accountant", ministry: "Controller General of Accounts (CGA), Ministry of Finance" },
  { sNo: 45, postCode: "D03", postName: "Accountant/Junior Accountant", ministry: "CGCA (Controller General of Communication Accounts), Ministry of Communications" },
  { sNo: 46, postCode: "D04", postName: "Accountant/Junior Accountant", ministry: "Department of Posts, Ministry of Communications" },
  { sNo: 47, postCode: "D05", postName: "Postal Assistant / Sorting Assistant (PA/SA)", ministry: "Department of Posts, Ministry of Communications" },
  { sNo: 48, postCode: "D06", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Office of Development Commissioner, Ministry of Micro, Small and Medium Enterprises" },
  { sNo: 49, postCode: "D07", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Ministry of Textiles" },
  { sNo: 50, postCode: "D08", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Central Bureau of Narcotics, Ministry of Finance" },
  { sNo: 51, postCode: "D09", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Indian Meteorological Department, Ministry of Earth Sciences" },
  { sNo: 52, postCode: "D10", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Director General Defence Estates (DGDE), Ministry of Defence" },
  { sNo: 53, postCode: "D11", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Agriculture Cooperation and Farmers Welfare, Ministry of Agriculture & Farmers Welfare" },
  { sNo: 54, postCode: "D12", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Atomic Energy" },
  { sNo: 55, postCode: "D13", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Ministry of Mines" },
  { sNo: 56, postCode: "D14", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Science and Technology, Ministry of Science & Technology" },
  { sNo: 57, postCode: "D15", postName: "Tax Assistant", ministry: "Central Board of Direct Taxes (CBDT)" },
  { sNo: 58, postCode: "D16", postName: "Tax Assistant", ministry: "Central Board of Indirect Taxes and Customs (CBIC), Ministry of Finance" },
  { sNo: 59, postCode: "D17", postName: "Sub-Inspector (Narcotics)", ministry: "Central Bureau of Narcotics, Ministry of Finance" },
  { sNo: 60, postCode: "D18", postName: "Accountant/Junior Accountant", ministry: "National Technical Research Organisation" },
  { sNo: 61, postCode: "D19", postName: "Accountant/Junior Accountant", ministry: "Department of Agriculture Cooperation and Farmers Welfare, Ministry of Agriculture & Farmers Welfare" },
  { sNo: 62, postCode: "D20", postName: "Accountant/Junior Accountant", ministry: "Intelligence Bureau (IB), Ministry of Home Affairs" },
  { sNo: 63, postCode: "D21", postName: "Auditor", ministry: "Controller General Of Defence Accounts (CGDA), Ministry of Defence" },
  { sNo: 64, postCode: "D22", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Border Roads Organization (BRO), Department of Defence" },
  { sNo: 65, postCode: "D23", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Central Information Commission (CIC)" },
  { sNo: 66, postCode: "D24", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Water Resources, River Development and Ganga Rejuvenation, Ministry of Jal Shakti" },
  { sNo: 67, postCode: "D25", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Department of Consumer Affairs, Ministry of Consumer Affairs, Food, & Public Distribution" },
  { sNo: 68, postCode: "D26", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Narcotics Control Bureau, Ministry of Home Affairs" },
  { sNo: 69, postCode: "D27", postName: "Upper Division Clerk(UDC)/Senior Secretariat Assistant(SSA)", ministry: "Ministry of Housing & Urban Affairs" },
]
